context:
  version: "0.6.4"

package:
  name: litterbox
  version: ${{ version }}

source:
  url: https://github.com/Gerharddc/Litterbox/archive/refs/tags/v${{ version }}.tar.gz
  sha256: fdd64fdcdaa340789bce32b56216dd673b294e38c0dff0639abd191ec21b1471

build:
  number: 1
  script:
    env:
      CARGO_PROFILE_RELEASE_LTO: fat
      CARGO_PROFILE_RELEASE_STRIP: symbols
    interpreter: nu
    content:
      - cd litterbox
      - cargo auditable install --path=.           --root=($env.PREFIX) --no-track --locked --bins
      - cargo auditable install --path=../lbx-init --root=($env.PREFIX) --no-track --locked --bins
      - cargo-bundle-licenses --format=yaml --output=../THIRDPARTY.yml
  skip: not linux

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-auditable
    - cargo-bundle-licenses
    - nushell

tests:
  - script:
      - litterbox --help
      - litterbox --version
      - lbx-init --help
      - lbx-init --version
  - package_contents:
      bin:
        - litterbox
        - lbx-init
      strict: true

about:
  summary: Somewhat isolated development environments
  description: |
    Litterbox is a Linux sandbox environment for developers. It provides some
    isolation between a containerised development environment and the host
    system, while also offering a repeatable and documented environment for
    development.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://litterbox.work/
  repository: https://github.com/Gerharddc/Litterbox

extra:
  recipe-maintainers:
    - salim-b
